-- Application bindings.
o.bind("SUPER + RETURN", "Terminal", { omarchy = "terminal" })
o.bind("SUPER + ALT + RETURN", "Tmux", { omarchy = "terminal-tmux" })
o.bind("SUPER + SHIFT + RETURN", "Browser", { omarchy = "browser" })
o.bind("SUPER + SHIFT + F", "File manager", { omarchy = "nautilus" })
o.bind("SUPER + ALT + SHIFT + F", "File manager (cwd)", { omarchy = "nautilus-cwd" })
o.bind("SUPER + SHIFT + B", "Browser", { omarchy = "browser" })
o.bind("SUPER + SHIFT + ALT + B", "Browser (private)", { omarchy = "browser --private" })
o.bind("SUPER + SHIFT + M", "Music", { omarchy = "or-focus spotify" })
o.bind("SUPER + SHIFT + ALT + M", "Music TUI", { tui = "cliamp", focus = true })
o.bind("SUPER + SHIFT + N", "Editor", { omarchy = "editor" })
o.bind("SUPER + SHIFT + D", "Docker", { tui = "lazydocker" })
o.bind("SUPER + SHIFT + G", "Signal", { launch = "signal-desktop", focus = "^signal$" })
o.bind("SUPER + SHIFT + O", "Obsidian", { launch = "obsidian", focus = "^obsidian$" })
o.bind("SUPER + SHIFT + W", "Typora", { launch = "typora --enable-wayland-ime" })
o.bind("SUPER + SHIFT + SLASH", "Passwords", { launch = "1password" })

-- Web app bindings.
o.bind("SUPER + SHIFT + A", "ChatGPT", { webapp = "https://chatgpt.com" })
o.bind("SUPER + SHIFT + ALT + A", "Grok", { webapp = "https://grok.com" })
o.bind("SUPER + SHIFT + C", "Calendar", { webapp = "https://app.hey.com/calendar/weeks/" })
o.bind("SUPER + SHIFT + E", "Email", { webapp = "https://app.hey.com" })
o.bind("SUPER + SHIFT + Y", "YouTube", { webapp = "https://youtube.com/" })
o.bind("SUPER + SHIFT + ALT + G", "WhatsApp", { webapp = "https://web.whatsapp.com/", focus = true })
o.bind("SUPER + SHIFT + CTRL + G", "Google Messages", { webapp = "https://messages.google.com/web/conversations", focus = true })
o.bind("SUPER + SHIFT + P", "Google Photos", { webapp = "https://photos.google.com/", focus = true })
o.bind("SUPER + SHIFT + S", "Google Maps", { webapp = "https://maps.google.com/", focus = true })
o.bind("SUPER + SHIFT + X", "X", { webapp = "https://x.com/" })
o.bind("SUPER + SHIFT + ALT + X", "X Post", { webapp = "https://x.com/compose/post" })

-- Master layout controls.
o.bind("SUPER + M", "Toggle layout", function()
  hl.exec_cmd("if hyprctl getoption general:layout -j 2>/dev/null | grep -q master; then hyprctl keyword general:layout dwindle; else hyprctl keyword general:layout master; fi")
end)
o.bind("SUPER + RETURN", "Promote window to master", function()
  hl.exec_cmd("hyprctl dispatch layoutmsg swaps")
end)
o.bind("SUPER + CTRL + PERIOD", "Master size +", function()
  hl.exec_cmd("hyprctl keyword master:mfact $(echo $(hyprctl getoption master:mfact -j | grep -oP '\\d+\\.\\d+') + 0.05 | bc)")
end)
o.bind("SUPER + CTRL + COMMA", "Master size -", function()
  hl.exec_cmd("hyprctl keyword master:mfact $(echo $(hyprctl getoption master:mfact -j | grep -oP '\\d+\\.\\d+') - 0.05 | bc)")
end)
o.bind("SUPER + CTRL + H", "Master left", function()
  hl.exec_cmd("hyprctl keyword master:orientation left")
end)
o.bind("SUPER + CTRL + L", "Master right", function()
  hl.exec_cmd("hyprctl keyword master:orientation right")
end)
o.bind("SUPER + CTRL + K", "Master top", function()
  hl.exec_cmd("hyprctl keyword master:orientation top")
end)
o.bind("SUPER + CTRL + J", "Master bottom", function()
  hl.exec_cmd("hyprctl keyword master:orientation bottom")
end)
o.bind("SUPER + CTRL + T", "Toggle split type", function()
  hl.exec_cmd("hyprctl dispatch layoutmsg togglesplit")
end)

hl.unbind("SUPER + CTRL + S")
o.bind("SUPER + CTRL + S", "Toggle shell", "toggle-shell")

-- Add extra bindings below.
-- o.bind("SUPER + SHIFT + R", "SSH", "alacritty -e ssh your-server")

-- Overwrite existing bindings with hl.unbind() first if needed.
hl.unbind("SUPER + SPACE")
o.bind("SUPER + SPACE", "Launcher", function()
  hl.exec_cmd("caelestia-launcher")
end)

-- Logitech MX Keys examples:
-- o.bind("SUPER + SHIFT + S", nil, "omarchy-capture-screenshot")
-- o.bind("SUPER + H", nil, "voxtype record toggle")
-- o.bind("SUPER + PERIOD", nil, { omarchy = "walker -m symbols" })
