# =============================================================================
# KONFIGURASI MONITOR HYPERLAND
# =============================================================================
# Dokumentasi: https://wiki.hyprland.org/Configuring/Monitors/
# Format: monitor = port, resolution, position, scale, [opsi]
# =============================================================================

env = GDK_SCALE,1
env = GDK_DPI_SCALE,1
env = GDK_FONT_SCALE,1

# Monitor laptop
monitor = eDP-1, 1920x1080@60, 0x0, 1

# HDMI TV akan di-mirror via autostart
monitor = HDMI-A-1, preferred, auto, 1
